yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='    '),
] 

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView 
from django.urls import path

from .views import SignUp


app_name = 'users'

urlpatterns = [
    path(
      'login/',
      LoginView.as_view(template_name='users/login.html'),
      name='login'
    ),
    path(
      'logout/',
      LogoutView.as_view(template_name='users/logged_out.html'),
      name='logout'
    ),
    path(
        'signup/',
        SignUp.as_view(), 
        name='signup'
    ),
    path(
        'password_change/',
         PasswordChangeView.as_view(template_name='users/password_change_form.html'),
         name='password_change'
    ),
] 

yatube/yatube/urls.py
# yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='urls')),
    path('auth/', include('django.contrib.auth.urls')), 
] 

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    ) 
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='posts',
                              blank=True, null=True)

yatube/users/models.py
from django.db import models

# Create your models here.

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username', 'email') 

yatube/posts/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Group, Post


def index(request):
    posts = Post.objects.all()[:10]
    context = {
            'posts': posts,
        }
    return render(request, 'posts/index.html', context)



def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
            'group': group,
            'posts': posts,
        }
    return render(request, 'group.html', context) 

yatube/users/views.py
from django.contrib.auth import get_user_model
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('posts:index')

yatube/templates/base.html
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
  <head>    
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
        {% block content %}
        {% endblock content %}   
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отсупом сверху и снизу -->            
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/group.html
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }} | Yatube
{% endblock title %}
{% block content %}
<div class="container">        
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  {% for post in posts %}
  <article>
    <ul>       
      <li>
        Автор: {{ post.author.first_name }} {{ post.author.last_name }}
      </li>
      <li>
        дата публикации: {{ post.pub_date|date:"d M Y" }}
      </li>
    </ul>      
    <p>
      {{ post.text }}
    </p>

  </article>
  {% if not forloop.last %}
    <hr>    
  {% endif %}
  {% endfor %}
</div> 
{% endblock content %}
  

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
  <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}
<header>
  <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
  <!-- В дальнейшем тут будет создано полноценное меню -->
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
       <!-- ссылка должна вести на главную страницу -->
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
        <span style="color:red">Ya</span>tube
      </a>
    </div>
  </nav>      
</header>

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Последние обновления на сайте
{% endblock title %}
  
{% block content %}
<div class="container">        
  <h1>Последние обновления на сайте</h1>
  {% for post in posts  %}
  <article>
    <ul>       
      <li>
        Автор: {{ post.author.first_name }} {{ post.author.last_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d M Y" }}
      </li>
    </ul>      
    <p>
      {{ post.text }}
    </p>
    
    {% if post.group %}
    <a href="{% url 'posts:group_list' 'post.group.slug' %}">все записи группы</a>
    {% else %}
    <a href="/">все записи группы</a>   
    {% endif %}

  </article>
  {% if not forloop.last %}
    <hr>    
  {% endif %}
  {% endfor %}
</div>  
</main>
{% endblock content %}
  

yatube/templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            
            {% comment %}
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
            {% endcomment %}
              
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  Изменить пароль
{% endblock title %}


{% block content %} 
<div class="container py-5"> 
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          
          {% for field in form.fields  %}
            {% for error in fields.errors %}
              <div class="alert alert-danger">
                {{ error }}
              </div>
            {% endfor %}            
          {% endfor %}
          {% for error in form.non_field_errors  %}
            <div class="alert alert-danger">
              {{ error }}
            </div>            
          {% endfor %}
            
          <form method="post" action="."> 
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                  <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div class="my-3 p-3">
                {{ field|addclass:"form-control" }}
              </div>
            {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button class="btn btn-primary" type="submit">Сменить пароль</button>
              </div>
            </div>
          </form>
        </div> 
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock content %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %} 